[package]
name = "git-static-build-failure"
version = "0.1.0"
edition = "2021"

[lib]
name = "testlib"
#crate-type = ["cdylib", "staticlib"]
crate-type = ["staticlib"]

[dependencies]
git2 = {version="0.18.3"}
